//go:build linux

package container

import (
	"errors"
	"fmt"
	"io"
	"os"
	"syscall"

	"minicontainer/internal/events"
)

const (
	runtimeInitStatusFD    uintptr = 4
	runtimeInitReadyByte   byte    = 0x5a
	runtimeInitFailureByte byte    = 0xe1
)

type runtimeInitStatusWriter struct {
	file *os.File
}

func openRuntimeInitStatusWriter() (*runtimeInitStatusWriter, error) {
	file := os.NewFile(runtimeInitStatusFD, "runtime-init-status")
	if file == nil {
		return nil, fmt.Errorf("runtime init status fd %d is unavailable", runtimeInitStatusFD)
	}
	// The kernel closing this descriptor during a successful exec is the
	// authoritative boundary between runtime initialization and payload life.
	syscall.CloseOnExec(int(file.Fd()))
	return &runtimeInitStatusWriter{file: file}, nil
}

func (s *runtimeInitStatusWriter) readyForExec() error {
	if s == nil || s.file == nil {
		return fmt.Errorf("runtime init status writer is nil")
	}
	if _, err := s.file.Write([]byte{runtimeInitReadyByte}); err != nil {
		return fmt.Errorf("report runtime init ready: %w", err)
	}
	return nil
}

// finish is called only when ContainerInit returns to Go. A successful
// syscall.Exec never runs defers; CLOEXEC closes the descriptor instead. Thus
// any returning error is explicitly marked as a runtime-initialization failure,
// including syscall.Exec failures that occur after READY was sent.
func (s *runtimeInitStatusWriter) finish(resultErr error) {
	if s == nil || s.file == nil {
		return
	}
	if resultErr != nil {
		_, _ = s.file.Write([]byte{runtimeInitFailureByte})
	}
	_ = s.file.Close()
}

// awaitPayloadExec accepts exactly READY followed by EOF. EOF before READY,
// FAILURE at either stage, malformed bytes, or pipe errors fail closed as
// runtime initialization failures. The EOF after READY is generated by CLOEXEC
// when the payload image successfully replaces the runtime init process.
//
// A staged lifecycle start is committed only at that exec boundary. Parent-side
// readiness merely permits initialization to continue and is not evidence that
// a payload ever started. Event persistence remains best effort: an observability
// write failure cannot revoke an already-successful exec.
func awaitPayloadExec(readPipe *os.File) error {
	if readPipe == nil {
		return fmt.Errorf("runtime init status reader is nil")
	}

	var first [1]byte
	if _, err := io.ReadFull(readPipe, first[:]); err != nil {
		return fmt.Errorf("payload exec was not confirmed: %w", err)
	}
	switch first[0] {
	case runtimeInitFailureByte:
		return fmt.Errorf("container runtime initialization failed before payload exec")
	case runtimeInitReadyByte:
		// Continue below and require CLOEXEC EOF.
	default:
		return fmt.Errorf("invalid runtime init status byte 0x%02x", first[0])
	}

	var second [1]byte
	_, err := io.ReadFull(readPipe, second[:])
	if err == io.EOF {
		_ = events.CommitPendingStart()
		return nil
	}
	if err != nil {
		return fmt.Errorf("confirm payload exec boundary: %w", err)
	}
	if second[0] == runtimeInitFailureByte {
		return fmt.Errorf("container runtime initialization failed while executing payload")
	}
	return fmt.Errorf("invalid post-ready runtime init status byte 0x%02x", second[0])
}

func joinRuntimeInitFailure(resultErr, initErr error) error {
	if initErr == nil {
		return resultErr
	}
	controlErr := &runtimeSetupError{err: fmt.Errorf("container initialization: %w", initErr)}
	return errors.Join(resultErr, controlErr)
}
